name: automate-newsletter-project-deploy
on:
  push:
    branches: [main,'*-sprint-*',ui_testing]
jobs:
  deply-staging:
    name: Deploy to staging
    environment:
      name: Staging
    runs-on: ubuntu-latest
    if: contains(github.event.ref, '-sprint-')
    steps:
    - uses: actions/checkout@v2
    - name: Run Deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /home/ubuntu/
          ./deploy.sh

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.10.8]
    env:
      MAIL_ID: ${{ secrets.MAIL.ID }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb        
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install msedge-selenium-tools
      - uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &
      - name: Run Test
        run: |
          cd tests/integration
          pip install -r requirements.txt
          python -m pytest --browser headless-chrome
